> 当前位置：【Java】01_Java基础  -> 1.3_Exception（异常处理）

# 第一章 异常简介

## 1、异常 - 概述

- 在Java中，把异常信息封装成了一个类，当出现了问题时，就会创建异常类对象并抛出异常相关的信息（如异常出现的位置、原因等）

## 2、避免异常的方法

- 开发中尽量使用 if 条件判断来避免异常的发生
- 但是过多的 if 条件判断会导致程序的代码加长、臃肿，可读性差



---

# 第二章 异常 & 错误

- ==java.lang.Throwable== 类是 Java 语言中错误（Error）和异常（Exception）的超类

## （1）Error 类

- 主要用于描述 Java 虚拟机无法解决的严重错误，通常无法编码解决，如：JVM 挂掉了等。
- 指程序在==运行期间==发生了某种错误（XxxError），Error错误通常没有具体的处理方式，程序将会结束运行，Error错误的发生往往都是系统级别的问题，都是jvm所在系统发生的，并反馈给jvm的，无法针对处理，只能修正代码

## （2）Exception 类

- 主要用于描述因编程错误或偶然外在因素导致的轻微错误，通常可以编码解决，如：0作为除数等。
- 指程序在==编译、运行期间==发生了某种异常（XxxException），可以对异常进行具体的处理，若不处理异常，程序将会结束运行



---

# 第三章 异常分类

## 1、编译异常 / 检测性异常

### 1.1 编译异常 - 概述

- 指在编译阶段都能被编译器检测出来的异常。

### 1.2 编译异常 - 处理

- 声明异常：throws
- 抛出异常：throw
- 捕获异常：try…catch…finally



## 2、运行时异常 / 非检测性异常

### 2.1 运行时异常 - 概述

- 抛出的异常是 RuntimeException 类，或者是他的子类

### 2.2 运行时异常 - 处理

- 方法内部抛出的异常是运行异常，new XXXException

- 方法定义中无需 throws 声明，调用者也无需处理此异常

- 运行异常一旦发生，不要处理，直接修改源代码（运行异常一旦发生，后面的代码没有执行的意义

### 2.3 RuntimeException 的子类

- ArithmeticException（ 算术异常）
- ArrayIndexOutOfBoundsException（数组下标越界异常）（extends IndexOutOfBoundsException extends RuntimeException）

- NullPointerException（空指针异常）（extends RuntimeException）
- ClassCastException（类型转换异常）
- NumberFormatException（数字格式异常）
- NoSuchElementException（无元素异常）（extends RuntimeException）



---

# 第四章 编译异常 - 处理详解

## 1、声明和抛出异常 throws

### 1.1 声明和抛出异常 - 概述

- 将问题标识出来，报告给调用者，声明方法可能发生的异常
- 如果方法内通过 throw 抛出了编译时异常，而没有捕获处理，那么必须通过 throws 进行声明，让调用者去处理

### 1.2 声明和抛出异常 - 格式

```java
访问权限修饰符 返回值类型 方法名称(形参列表) throws 异常类型1,异常类型2,...{ 
    方法体; 
}

// 举例
public void show() throws IOException{}
```



## 2、捕获异常

### 2.1 捕获异常 - 概述

- 当程序执行过程中发生异常但又没有手动处理时，则由Java虚拟机采用默认方式处理异常，而默认处理方式就是：打印异常的名称、异常发生的原因、异常发生的位置以及终止程序。

- 检测异常，并传递给catch处理，并在finally中进行资源释放

### 2.2 捕获异常 - 格式

- 一般写法（编写多个catch分支时，小类型放在大类型的前面）

```java
try {
 // 编写可能发生异常的代码; 
}
catch(异常类型 引用变量名) {
 // 编写针对该类异常的处理代码；
 // 捕获异常 - 常用方法
}
...
finally {
 // 编写无论是否发生异常都要执行的代码（通常用于进行善后处理）
}
```

- 懒人写法（catch分支，写最大类型 Exception）

```java
try {
 // 编写可能发生异常的代码; 
}
catch(Exception e) {
 // 编写针对该类异常的处理代码；
 // 捕获异常 - 常用方法
}
...
finally {
 // 编写无论是否发生异常都要执行的代码（通常用于进行善后处理）
}
```



### 2.3 捕获异常 - 执行顺序

- 当==没有发生异常时==的执行流程：a b c e
- 当==发生异常时==的执行流程：a b d e

```java
try {
 a;
 b;  // 假设此处为可能发生异常的语句
 c;
}catch(Exception e) {
 d; 
}finally {
 e;
}
```



### 2.4 捕获异常 - 常用方法

#### （1）getMessage 方法

- 返回该异常的详细信息字符串，即异常提示信息

- 对异常信息的详细描述

#### （2）toString 方法

- 返回该异常的名称与详细信息字符串

- 对异常信息的简短描述

#### （3）printStackTrace 方法

- 在控制台输出该异常的名称与详细信息字符串、异常出现的代码位置

- 将异常信息追踪到标准的错误流（异常信息最全，JVM默认调用方法也是这个方法）



## 3、示例

```java
// 导包
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

....（代码）

// 声明静态变量
private static final Logger logger = LoggerFactory.getLogger(ParamConfigServiceImpl.class);

....（代码）

// 使用
try {
    getBaseDao().update("ParamConfigMapper.saveParamConfig", inputObject.getParams());
} catch (Exception e) {
    logger.error("保存失败,异常信息如下:message:{}", e.getMessage());
    e.printStackTrace();   // 打印完整的异常信息
}
```



---

# 第五章 自定义异常 throw（手动抛出异常）

## 1、自定义 xxxException 异常类，继承 Exception 类或其子类

### 1.1 extends Exception

```java
public class CustomException extends Exception {
    // 必须提供一个空参构造器
    public CustomException() {
		super();
	}

    // 构造方法中，super将异常信息传递给父类
    public CustomException(String message) {
		super(message);
	}
}
```

### 1.2 extends RuntimeException

```java
public class CustomRuntimeException extends RuntimeException { // 此处继承运行时异常
    // 必须提供一个空参构造器
    public CustomRuntimeException() {
    }

    // 构造方法中，super将异常信息传递给父类
    public CustomRuntimeException(String message) {
        super(message);
    }
}
```



## 2、抛出异常 throw

- 调用了抛出异常的方法，不处理编译失败 (try catch、throws)

- 使用格式

```java
// throw 用在方法内，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行
// throw 后面，必须写 new 对象，必须是异常的对象，必须是 Exception 或者子类
throw new 异常类名(参数);
```

### 2.1 extends Exception

```java
// 传递成绩，计算成绩的平均数（成绩没有负数，需要抛出异常，停止运算）
// ...表示可变参数（参数个数不确定，至少一个）
private static int getAvg(int... source) throws CustomException {
   int sum = 0;
   for (int s : source) {
      if (s < 0) {
         throw new CustomException("成绩错误 " + s);
      }
      sum = sum + s;
   }
   return sum / source.length;
}
```

### 2.2 extends RuntimeException

```java
// 传递成绩，计算成绩的平均数（成绩没有负数，需要抛出异常，停止运算）
// ...表示可变参数（参数个数不确定，至少一个）
private static int getAvg(int... source) {
   int sum = 0;
   for (int s : source) {
      if (s < 0) {
         throw new CustomRuntimeException("成绩错误 " + s);
      }
      sum = sum + s;
   }
   return sum / source.length;
}
```



## 3、测试

### 3.1 extends Exception

```java
public static void main(String[] args) throws CustomException {
   int avg = getAvg(50, 60, -70, 80);
   System.out.println(avg);  // 报异常
}
```

### 3.2 extends RuntimeException

```java
public static void main(String[] args) {
   int avg = getAvg(50, 60, -70, 80);
   System.out.println(avg);  // 报异常
}
```



## 4、总结 - 自定义异常

- 步骤1：编译时异常继承 Exception，运行时异常继承 RuntimeException
- 步骤2：构造方法中，super 将异常信息传递给父类
- 步骤3：提供空参构造方法（因为看到 Java 中的异常描述类中有提供对异常对象的初始化方法）

